server:
  servlet:
    context-path: /api
spring:
  port: ${SERVER_PORT:8080}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${SERVER_URL:jdbc:postgresql://localhost:5432/user}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-root.xml
    default-schema: public
logging:
  level:
    org.springframework: ERROR
    com.com.ferru97: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"

s4f:
  security:
    bcryptStrength: ${BYCRYPT_STRENGTH:10}
    bcryptRandomSeed: ${BYCRYPT_SEED:Uihu*P$F$wg6S&XYbdNW}